import type { Metadata } from "next";
import "./globals.css";
import MainNavigation from "@/components/layouts/MainNavigation";
import MainFooter from "@/components/layouts/MainFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainNavigation />
        <main>{children}</main>
        <MainFooter />
      </body>
    </html>
  );
}
